# Generated by Django 4.1 on 2022-09-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ocorrencias',
            fields=[
                ('numero', models.IntegerField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('problema', models.TextField()),
                ('descricao', models.TextField()),
                ('equipamento', models.CharField(max_length=15)),
                ('contato', models.CharField(max_length=100)),
                ('celula', models.CharField(max_length=11)),
                ('setor', models.CharField(max_length=30)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'tb_ocorrencias',
            },
        ),
    ]
