# Generated by Django 4.1 on 2022-09-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('at', '0003_alter_ocorrencias_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.TextField(max_length=150)),
                ('descricao', models.TextField(max_length=150)),
                ('equipamento', models.CharField(max_length=15)),
                ('contato', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('setor', models.CharField(max_length=30)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'tb_ocorrencia',
            },
        ),
        migrations.DeleteModel(
            name='ocorrencias',
        ),
    ]
